---
title: "Model selection diagnostic"
author: "Lorenzo Tarricone"
date: "23/12/2021"
output: 
  html_document:
    theme: paper
    toc: true
    df_print: paged
    code_download: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

We start by loading the needed libraries 
```{r}
library(tidyverse)
library(olsrr)
library(ggplot2)
```

Now we take an existing dataframe and we try to cut out some outliers, in our case we remove the datas from USA and Canada

```{r}
cancercopy <- subset(Cancer_final, Entity!= "United States" & Entity != "Canada")
modelcopy = lm( Cancer~ Smoking + Obesity + GDP + Age + AirPoll + Alcool, data = cancercopy)
ols_plot_resid_qq(modelcopy)
ols_test_normality(modelcopy)
ols_test_correlation(modelcopy)
ols_plot_resid_hist(modelcopy)
kop = residuals.lm(modelcopy)
hist(kop, breaks = 50)



plot(modelcopy)
summary(modelcopy)
```


```{r}
x = modelcopy$residuals
m = mean(x)
std = sd(x)
hist(x, density = 20, breaks = 20, probability = TRUE,
     main = "Histogram of the residuals and fitted normal density",
     xlab = "residuals", ylab = "Density")
curve(dnorm(x, mean = m, sd = std), col = "darkblue", lwt = 2, add = TRUE, yaxt = "n")

```

